apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: java-deployment
spec:
  selector:
    matchLabels:
      app: java-k8s
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: java-k8s
    spec:
      containers:
        - name: java-k8s
          image: europe-west1-docker.pkg.dev/oval-cyclist-426414-p0/java-app/my-app1 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster



---
